---
- name: Firefox PPA added
  become: yes
  apt_repository:
    repo: ppa:ubuntu-mozilla-security/ppa
    state: present
    update_cache: True
- name: Firefox installed
  become: yes
  apt:
    name: firefox
    state: present