---
- name: Install common desktop packages
  become: yes
  package:
    name:
      - xclip
      - fonts-hack
      - gnome-tweaks
      - terminator
- name: Install terminator config
  copy:
    src: terminator-config.ini
    dest: ~/.config/terminator/config
