---
- name: Install ROS 2 for Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'
- name: Ensure latest pip
  pip:
    name: pip
    state: latest
- name: Install argcomplete
  pip:
    name: argcomplete
    state: present
- name: rosdep initialized
  become: yes
  command:
    cmd: rosdep init
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
- name: rosdep updated
  become: no
  command:
    cmd: rosdep update