---
# https://docs.ros.org/en/galactic/Installation/Ubuntu-Install-Debians.html
- name: Universe respository enabled
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
    state: present
  become: yes
- name: ROS 2 GPG Key authorized
  apt_key:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
    keyring: /usr/share/keyrings/ros-archive-keyring.gpg
    state: present
  become: yes
- name: ROS 2 apt repository added
  apt_repository:
    repo: deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main
    filename: ros2
    state: present
  become: yes
- name: ros-base installed
  apt:
    name: ros-{{ ros_distro }}-ros-base
    state: present
    update_cache: yes
  become: yes
- name: colcon extensions installed
  apt:
    name: python3-colcon-common-extensions
    state: present
  become: yes
- name: rosdep installed
  apt:
    name: python3-rosdep
    state: present
  become: yes
- name: vcstool installed
  apt:
    name: python3-vcstool
    state: present
  become: yes
- name: pip installed
  apt:
    name: python3-pip
    state: present
  become: yes