---
- name: vscode ubuntu install
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'
- name: Ensure config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/Code/User"
    state: directory
- name: Copy config
  copy:
    src: settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"