---
- name: microsoft key added
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: present
- name: vscode repository added
  become: yes
  apt_repository:
    repo: deb [arch={{ 'amd64' if ansible_architecture == 'x86_64'}}] https://packages.microsoft.com/repos/vscode stable main
    filename: ros2
    state: present
- name: vscode installed
  become: yes
  apt:
    name: code
    state: present
    update_cache: yes