---
- name: Download steam.deb
  get_url:
    url: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
    dest: /tmp/steam.deb
- name: Install steam
  become: yes
  apt:
    deb: /tmp/steam.deb
    state: present
