---
- name: Enable RPM Fusion
  become: yes
  dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
- name: Install steam
  become: yes
  dnf:
    name: steam
    state: present
