---
- name: Create plotjuggler ws
  file:
    path: ~/src/plotjuggler_ws
    state: directory
- name: Clone plotjuggler repo
  git:
    repo: https://github.com/facontidavide/PlotJuggler.git
    dest: ~/src/plotjuggler_ws/plotjuggler
- name: Clone plotjuggler ros plugins repo
  git:
    repo: https://github.com/facontidavide/PlotJuggler.git
    dest: ~/src/plotjuggler_ws/plotjuggler-ros-plugins
- name: Install debian dependencies
  become: yes
  apt:
    name:
      - qtbase5-dev
      - libqt5svg5-dev
      - libqt5websockets5-dev
      - libqt5opengl5-dev
      - libqt5x11extras5-dev
      - libprotoc-dev
      - libiberty-dev
  state: present
  when: ansible_facts['os_family'] == 'Debian'
- name: Install fedora dependencies
  become: yes
  dnf:
    name:
    - qt5-qtbase-devel
    - qt5-qtsvg-devel 
    - qt5-websockets-devel 
    - qt5-qtopendl-devel
    - qt5-qtx11extras-devel
  state: present
  when: ansible_facts['os_family'] == 'RedHat'
- name: Create build directory
  file:
    path: ~/src/plotjuggler/build
    state: directory
- name: Configure with cmake
  command:
    chdir: ~/src/plotjuggler/build
    cmd: cmake ..
    creates: ./Makefile
- name: Build
  command:
    chdir: ~/src/plotjuggler/build
    cmd: make
    creates: ./src/bluetoothd
- name: Install plotjuggler
  become: yes
  command:
    chdir: ~/src/plotjuggler/build
    cmd: make install
    creates: /usr/local/libexec/bluetooth/bluetoothd
  register: bluez_installed
