---
- name: Create plotjuggler workspace
  file:
    path: "{{ plotjuggler_workspace }}/src"
    state: directory
- name: Clone plotjuggler repo
  git:
    repo: https://github.com/facontidavide/PlotJuggler.git
    dest: "{{ plotjuggler_workspace }}/src/plotjuggler"
- name: Clone plotjuggler ros plugins repo
  git:
    repo: https://github.com/PlotJuggler/plotjuggler-ros-plugins.git
    dest: "{{ plotjuggler_workspace }}/src/plotjuggler-ros-plugins"
    version: galactic
- name: Clone plotjuggler msgs
  git:
    repo: https://github.com/PlotJuggler/plotjuggler_msgs.git
    dest: "{{ plotjuggler_workspace }}/src/plotjuggler_msgs"
- name: Install dependencies
  become: yes
  shell:
    chdir: "{{ plotjuggler_workspace }}"
    cmd: |
      . /opt/ros/{{ ros_distro }}/setup.sh
      rosdep install --from-paths src --ignore-src --rosdistro={{ ros_distro }} -y
- name: Extra dependencies
  become: yes
  package:
    # This is needed because building gdb from source adds statically-linked bfd
    name: libiberty-dev
  state: present
- name: Build
  shell:
    chdir: "{{ plotjuggler_workspace }}"
    cmd: |
      . /opt/ros/{{ ros_distro }}/setup.sh
      colcon build --symlink-install