---
- name: Install zsh
  become: yes
  package:
    name: zsh
    state: present
- name: Clone Oh My Zsh repo
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/src/ohmyzsh
- name: Clone Zsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/src/zsh-autosuggestions
- name: Set shell_* startup file facts
  set_fact:
    shell_rc: ~/.zshrc
    shell_env: ~/.zshenv
    shell_ext: zsh
- name: Oh My Zsh setup
  blockinfile:
    path: "{{ shell_rc }}"
    create: yes
    insertbefore: BOF
    marker_begin: ohmyzsh-setup-begin
    marker_end: ohmyzsh-setup-end
    block: |
      export ZSH="$HOME/src/ohmyzsh"
      ZSH_THEME="agnoster"
      DEFAULT_USER="{{ ansible_user_id }}"
      plugins=(git)
      source $ZSH/oh-my-zsh.sh
      source ~/src/zsh-autosuggestions/zsh-autosuggestions.zsh
- name: Change default shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
- name: Source site specific setup
  lineinfile:
    path: "{{ shell_rc }}"
    line: '[ -s "$HOME/.setup" ] && source "$HOME/.setup"'
    regexp: source.*\.setup
