---
# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: Download AWS CLI v2
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip
    dest: /tmp/
    remote_src: yes
- name: Install AWS CLI v2
  command:
    cmd: /tmp/aws/install
    become: yes