---
- name: Ensure git is installed
  package:
    name: git
    state: present
- name: Add .gitconfig
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
- name: Set GIT_PAGER
  lineinfile:
    path: "{{ shell_env }}"
    create: yes
    line: export GIT_PAGER=cat
  when: shell_env is defined
