---
- name: Download go
  get_url:
    checksum: sha256:{{ go_checksum }}
    dest: /tmp/go.tar.gz
    url: https://go.dev/dl/go{{ go_version }}.linux-{{ deb_architecture }}.tar.gz
- name: Extract go
  become: yes
  unarchive:
    creates: "{{ go_dir }}"
    remote_src: yes
    src: /tmp/go.tar.gz
    dest: "{{ go_dir | dirname }}"
- name: Add go to PATH
  become: yes
  vars:
    go_bin_dir: "{{ (go_dir, 'bin') | path_join }}"
  # https://stackoverflow.com/a/56561538/5850658
  lineinfile:
    path: /etc/environment
    regexp: 'PATH=(["])((?!.*?{{ go_bin_dir }}).*?)(["])$'
    line: 'PATH=\1\2:{{ go_bin_dir }}\3'
    backrefs: yes
