---
# https://docs.ros.org/en/galactic/Installation/Ubuntu-Install-Debians.html
- name: Remove old docker packages
  become: yes
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
- name: Docker Key authorized
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  become: yes
- name: Docker apt repository added
  apt_repository:
    # TODO: handle aarch64 to arm64
    repo: deb [arch={{ deb_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  become: yes
- name: apt-utils installed
  become: yes
  apt:
    name: apt-utils
- name: Docker Engine Installed
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: yes
- name: Docker service disabled (use socket activation)
  become: yes
  systemd:
    name: docker.service
    enabled: no
