---
- name: Download bluez source
  get_url:
    url: http://www.kernel.org/pub/linux/bluetooth/bluez-{{ bluez_version }}.tar.xz
    checksum: sha256:{{ bluez_checksum }}
    dest: /tmp/bluez.tar.gz
- name: Extract bluez source
  become: yes
  unarchive:
    src: /tmp/bluez.tar.gz
    dest: "{{ bluez_source_dir | dirname }}"
    remote_src: yes
    creates: "{{ bluez_source_dir }}"
- name: Install necessary headers and libraries
  become: yes
  package:
    name:
      - libglib2.0-dev
      - libusb-dev
      - libdbus-1-dev
      - libudev-dev
      - libical-dev
      - libreadline-dev
      - python3-docutils
    state: present
- name: Configure bluez
  become: yes # maybe get rid of this with chown
  command:
    chdir: "{{ bluez_source_dir }}"
    cmd: ./configure
    creates: ./Makefile
- name: Build bluez
  become: yes # maybe get rid of this with chown
  command:
    chdir: "{{ bluez_source_dir }}"
    cmd: make
    creates: ./src/bluetoothd
- name: Install bluez
  become: yes
  command:
    chdir: "{{ bluez_source_dir }}"
    cmd: make install
    creates: /usr/local/libexec/bluetooth/bluetoothd
  register: bluez_installed
- name: Reload systemd
  become: yes
  systemd:
    daemon_reload: yes
  when: bluez_installed.changed