---
- name: Install Debian dependencies
  become: yes
  apt:
    name:
      - pkg-config
      - build-essential
      - autoconf
      - bison
      - re2c
      - libxml2-dev
      - libsqlite3-dev
